GET http://localhost:5159/games


###
Get http://localhost:5159/games/5


###
POST http://localhost:5159/games
Content-Type: application/json

{
    "name": "Super Mario Bros. Wonder 1",
    "genreId": 3,
    "price": "39.99",
    "releaseDate": "2023-10-20"
}

###
PUT http://localhost:5159/games/5
Content-Type: application/json

{
    "name": "Super Mario Bros. Wonder 2",
    "genre": "Platformer",
    "price": "39.99",
    "releaseDate": "2023-10-20"
}

###
DELETE http://localhost:5159/games/1
